### ISSUE TITLE
error with logs

### ISSUE THREAD

**Issue by phampyk** [catter1/LogCutter#1]
Hello! I recently installed this datapack and when tried the crimson wood would give me both the warped and crimson, and when tried the warped didn't show any, probably just a little mistake, but it would be great if you could fix it. 
Thank you

Edit: I'm pretty sure the problem is [stripped_warped_stem_from_warped_stem_stonecutting.json](https://github.com/catter1/LogCutter/blob/f7fd8f855506418934e8bca8f912db5045bbe649/data/logcutter/recipes/stripped_warped_stem_from_warped_stem_stonecutting.json)

**Comment by catter1** [comment]
Sorry for that extremely long wait for such a simple fix - this has been very low on my todo list. New version should be out now, along with a 1.20 update to support bamboo/cherry wood!
